default: &default
  images:
    work_dir: /tmp/lens-manage/images
    src_path: /objs/images
    objs_path: /images
    convert:
      font_path: /app/assets/fonts/ipag.ttc
  nginx:
    pid_dir: /home/app/run
  cache:
    conoha_container_data: /tmp/cache/conoha_container_data.json
  pid:
    lock_file: /tmp/cache/lock_file.pid

test:
  <<: *default

development:
  <<: *default

production:
  <<: *default
